// Code generated by MockGen. DO NOT EDIT.
// Source: secretsmanagerx/interface.go
//
// Generated by this command:
//
//	mockgen -source secretsmanagerx/interface.go -destination secretsmanagerx/mock_interface.go -package secretsmanagerx
//

// Package secretsmanagerx is a generated GoMock package.
package secretsmanagerx

import (
	context "context"
	reflect "reflect"

	secretsmanager "github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretsManagerGetSecretValueAPI is a mock of SecretsManagerGetSecretValueAPI interface.
type MockSecretsManagerGetSecretValueAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSecretsManagerGetSecretValueAPIMockRecorder
	isgomock struct{}
}

// MockSecretsManagerGetSecretValueAPIMockRecorder is the mock recorder for MockSecretsManagerGetSecretValueAPI.
type MockSecretsManagerGetSecretValueAPIMockRecorder struct {
	mock *MockSecretsManagerGetSecretValueAPI
}

// NewMockSecretsManagerGetSecretValueAPI creates a new mock instance.
func NewMockSecretsManagerGetSecretValueAPI(ctrl *gomock.Controller) *MockSecretsManagerGetSecretValueAPI {
	mock := &MockSecretsManagerGetSecretValueAPI{ctrl: ctrl}
	mock.recorder = &MockSecretsManagerGetSecretValueAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretsManagerGetSecretValueAPI) EXPECT() *MockSecretsManagerGetSecretValueAPIMockRecorder {
	return m.recorder
}

// GetSecretValue mocks base method.
func (m *MockSecretsManagerGetSecretValueAPI) GetSecretValue(ctx context.Context, params *secretsmanager.GetSecretValueInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSecretValue", varargs...)
	ret0, _ := ret[0].(*secretsmanager.GetSecretValueOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretValue indicates an expected call of GetSecretValue.
func (mr *MockSecretsManagerGetSecretValueAPIMockRecorder) GetSecretValue(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretValue", reflect.TypeOf((*MockSecretsManagerGetSecretValueAPI)(nil).GetSecretValue), varargs...)
}
