name: test

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile**'
      - '!README.md'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile**'
      - '!README.md'

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Setup Golang caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: Run Go tests
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          slug: citadel2024/aws-toolkit
